apiVersion: v1
kind: ConfigMap
metadata:
  name: udeaku-config
  namespace: udeaku-carespring
  labels:
    app: udeaku-carespring
data:
  NODE_ENV: "production"
  PORT: "5001"
  CONTACT_EMAIL: "carespringsup@gmail.com"
  WHATSAPP_NUMBER: "+2347036152774"
  FORM_SUBMISSION_ENDPOINT: "/api/register"
  ALLOWED_ORIGINS: "https://udeakucarespringsupportfoundation.org,https://www.udeakucarespringsupportfoundation.org"
